export function speakers() {
    return [
        {
            name: 'Sunny Lu',
            company: 'Vechain',
            img: '/speakers/1)Sunny-Lu.png',
            desc: 'Sunny Lu is a renowned crypto and blockchain entrepreneur who co-founded and serves as CEO of the VeChain Foundation, the core developer behind the VeChain blockchain network — which is tailored for supply chain tracking and management. Lu also co-founded BitSE, the China-based firm that initially managed VeChain before it became a separate entity.',
            charge: 'CEO',
            link: 'https://www.linkedin.com/in/sunny-lu-55456915/',
        },
        {
            name: 'Helen Hai',
            company: 'Binance',
            img: '/speakers/2)Helen-Hai.png',
            desc: 'Helen is Executive VP of Binance organization including head of EU, UK and Africa region, head of Global Fiat, P2P and Custody business, also head of Binance Charity Foundation; Helen also built NFT and Fan token business for Binance.',
            charge: 'Executive VP',
            link: 'https://www.linkedin.com/in/helen-hai-754a467/',
        },
        {
            name: 'Alex Zinder',
            company: 'Ledger Enterprise',
            img: '/speakers/3)Alex-Zinder.png',
            desc: 'Alex is the Head of Ledger Enterprise bringing more than 15 years of experience in driving the adoption of emerging technologies in major financial services organizations. Alex joined Ledger Enterprise in March 2021 after almost two decades in capital markets technology. He previously worked at Nasdaq as director of global software development and associate vice president of enterprise architecture roles. More recently, Alex was working on the next generation of digital capital markets infrastructure in a senior advisor and head of architecture role at SIX Digital Exchange.',
            charge: 'Head',
            link: 'https://www.linkedin.com/in/alex-zinder/',
        },
        {
            name: 'Gracy Chen',
            company: 'Bitget',
            img: '/speakers/4)Gracy-Chen.png',
            desc: 'Gracy Chen is the managing director of Bitget and oversees the growth and expansion of global markets, strategy, execution, business and corporate development of Bitget. She started her journey to crypto world since 2014, and has been an investor in the early days of BitKeep, Asia’s leading decentralised wallet',
            charge: 'Managing Director',
            link: 'https://www.linkedin.com/in/gracychen/',
        },
        {
            name: 'Mohammed Alblooshi',
            company: 'Dubai International Financial Centre Authority',
            img: '/speakers/5)Mohammed-Alblooshi.png',
            desc: 'Mohammed AlBlooshi contributes to the growth of the DIFC by developing managing its FinTech & Innovation functions in line with the Dubai Vision of a global business hub for tech. AlBlooshi is a specialist in FinTech & Innovation and Business Development',
            charge: 'Head',
            link: 'https://www.linkedin.com/in/mohammad-alblooshi-2499b54a/',
        },
        {
            name: 'Max Kordek',
            company: 'Lisk',
            img: '/speakers/6)Max-Kordek.png',
            desc: 'Globally recognized blockchain visionary, Max leads strategy & business at Lisk Foundation, the not-for-profit arm of the Javascript blockchain app platform Lisk, which has raised over 14,000 of well-known B’currency on its initial boost, making it one of the most successful crowdfunding projects in history, while Lisk itself was valued at over$400,000,000 at its peak. ',
            charge: 'Co-Founder & President',
            link: 'https://www.linkedin.com/in/maxkordek/',
        },
        {
            name: 'Nena Dokuzov',
            company: 'Alserkal Group',
            img: '/speakers/7)Nena-Dokuzov.png',
            desc: 'Nena Dokuzov is the Head of the Project Group for New Economy and Blockchain Technology at the Ministry of Economic Development and Technology of Slovenia. She has encouraged and led the preparation of the Action Plan for Blockchain Technology adopted by the Slovenian government in 2018.',
            charge: 'Blockchain Technologies Coordinator',
            link: 'https://www.linkedin.com/in/nena-dokuzov-27a9883a/',
        },
        {
            name: 'Reece Merrick',
            company: 'Ripple',
            img: '/speakers/8)Reece-Merrick.png',
            desc: 'Reece is Senior Director of Global Strategic Partners at Ripple where he leads relationships with key financial institutions & crypto partners adopting blockchain-based payments and crypto liquidity solutions to enable cross-border payments.',
            charge: 'Senior Director',
            link: 'https://www.linkedin.com/in/reece-merrick-a4184622/',
        },
        {
            name: "Dina Sam'an",
            company: 'CoinMENA',
            img: "/speakers/9)Dina-Sam'an.png",
            desc: "Dina Sam'an is the co-founder and Managing Director of CoinMENA, a fully regulated, Sharia-compliant crypto assets exchange serving the MENA region and based out of the Kingdom of Bahrain. CoinMENA addresses the gap that exists in the regional market today by allowing users to deposit, trade, and withdraw crypto assets in a safe, trustworthy, transparent, and regulated way.",
            charge: 'Co-Founder',
            link: 'https://www.linkedin.com/in/dinasaman/',
        },
        {
            name: 'Jean Charles-Gaudechon',
            company: 'OneFootball Labs',
            img: '/speakers/10)Jean-Charles-Gaudechon.png',
            desc: 'Global football media platform, OneFootball, has appointed longtime Electronic Arts veteran, Jean-Charles Gaudechon as the CEO of OneFootball Labs, a new joint venture launched in partnership with Animoca Brands.',
            charge: 'CEO',
            link: 'https://www.linkedin.com/in/jcgaudechon/',
        },
        {
            name: 'Nicole Purin',
            company: 'OKX',
            img: '/speakers/11)Nicole-Purin.png',
            desc: 'Nicole is an experienced international finance lawyer who has worked with trad-fi heavyweights across investment banking, derivatives and capital markets. She will be instrumental in ensuring the compliance of the OKX brand internationally.',
            charge: 'Deputy General Counsel',
            link: 'https://www.linkedin.com/in/nicole-purin-9a431/',
        },
        {
            name: 'Jason Allegrante',
            company: 'Fireblocks',
            img: '/speakers/12)Jason-Allegrante.png',
            desc: 'Jason Allegrante is the Chief Legal & Compliance Officer at Fireblocks, where he manages a broad portfolio of legal, regulatory, commercial and compliance matters.  Prior to Fireblocks, he worked in the Financial Institution Supervision Group at the Federal Reserve Bank of New York and practiced law at the international firms Linklaters LLP and Davis Polk & Wardwell.',
            charge: 'Chief Legal & Compliance Officer',
            link: 'https://www.linkedin.com/in/jasonallegrante/',
        },
    ]
}
